config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.nynet.views import home_view
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nynet/', include('core.nynet.urls')),
    path('', home_view, name='home'),
    path('login/', include('core.login.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/nynet/urls.py
from django.urls import path

from core.nynet.views import ProductListView, ProductDatatableView, ProductCreateView, InvoiceDatatableView, \
    InvoiceCreateView, InventoryDatatableView, InventoryCreateView, ProductUpdateView, InvoiceUpdateView, \
    ProductDeleteView, InvoiceDeleteView, CustomerDeleteView, CustomerCreateView, CustomerUpdateView, \
    InventoryUpdateView, CustomerDatatableView, InventoryDeleteView

app_name = 'nynet'

urlpatterns = [
    # Product
    path('products/list/', ProductListView.as_view(), name='product_list'),
    path('products/datatable/', ProductDatatableView.as_view(), name='datable_product'),
    path('products/add/', ProductCreateView.as_view(), name='create_product'),
    path('products/edit/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),

    # Invoice
    path('invoices/datatable/', InvoiceDatatableView.as_view(), name='datable_invoice'),
    path('invoices/add/', InvoiceCreateView.as_view(), name='create_invoice'),
    path('invoices/edit/<int:pk>/', InvoiceUpdateView.as_view(), name='update_invoice'),
    path('invoices/delete/<int:pk>/', InvoiceDeleteView.as_view(), name='delete_invoice'),

    # Inventory
    path('inventories/datatable/', InventoryDatatableView.as_view(), name='datable_inventory'),
    path('inventories/add/', InventoryCreateView.as_view(), name='create_inventory'),
    path('inventories/edit/<int:pk>/', InventoryUpdateView.as_view(), name='update_inventory'),
    path('inventories/delete/<int:pk>/', InventoryDeleteView.as_view(), name='delete_inventory'),

    # Customer
    path('customers/datatable/', CustomerDatatableView.as_view(), name='datable_customer'),
    path('customers/add/', CustomerCreateView.as_view(), name='create_customer'),
    path('customers/edit/<int:pk>/', CustomerUpdateView.as_view(), name='update_customer'),
    path('customers/delete/<int:pk>/', CustomerDeleteView.as_view(), name='delete_customer'),

]

core/nynet/forms.py
from django.forms import ModelForm, TextInput, Textarea, ClearableFileInput, NumberInput, EmailInput, Select, \
    DateTimeInput
from .models import Product, Invoice, Inventory, Customer


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'name': TextInput(
                attrs={
                    'class': 'input',
                    'placeholder': 'Name of product',
                    'type': 'text',
                }
            ),
            'description': Textarea(
                attrs={
                    'class': 'textarea',
                    'placeholder': 'Description of product',
                }
            ),

            'image': ClearableFileInput(
                attrs={
                    'class': 'file-input',
                    'type': 'file',
                }
            ),
            'price': NumberInput(
                attrs={
                    'class': 'input'
                }
            )

        }
        exclude = ['user_updated', 'user_creation']

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data


class InvoiceForm(ModelForm):
    class Meta:
        model = Invoice
        fields = '__all__'
        widgets = {
            'subtotal': NumberInput(
                attrs={
                    'class': 'input',
                    'readonly': '',
                    'name': 'subtotal',
                }
            ),
            'total': NumberInput(
                attrs={
                    'class': 'input',
                    'readonly': '',
                    'name': 'total',
                }
            ),
            'iva': NumberInput(
                attrs={
                    'class': 'input',
                    'name': 'iva',
                }
            ),
            'date_joined': DateTimeInput(
                attrs={
                    'type': 'date',
                    'name': 'date_joined',

                }
            ),
        }
        exclude = ['user_updated', 'user_creation']

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data


class InventoryForm(ModelForm):
    class Meta:
        model = Inventory
        fields = '__all__'
        widgets = {
            'stock': NumberInput(
                attrs={
                    'class': 'input'
                }
            )
        }
        exclude = ['user_updated', 'user_creation']

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        widgets = {
            'first_name': TextInput(
                attrs={
                    'class': 'input',
                    'placeholder': 'First name',
                    'type': 'text',
                }
            ),
            'last_name': TextInput(
                attrs={
                    'class': 'input',
                    'placeholder': 'Last name',
                    'type': 'text',
                }
            ),
            'dni': NumberInput(
                attrs={
                    'class': 'input'
                }
            ),
            'address': TextInput(
                attrs={
                    'class': 'input',
                    'placeholder': 'Address',
                    'type': 'text',
                }
            ),
            'email': EmailInput(
                attrs={
                    'class': 'input',
                    'type': 'email',
                    'placeholder': 'Email',
                }
            ),
            'amount_invoices': NumberInput(
                attrs={
                    'class': 'input'
                }
            ),
        }
        exclude = ['user_updated', 'user_creation']

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

core/nynet/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from core.nynet.forms import ProductForm, InvoiceForm, InventoryForm, CustomerForm
from core.nynet.models import Product, Invoice, Inventory, Customer

import json


def home_view(request):
    context = {
    }
    return render(request, 'index.html', context)


# Product

class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'product/list-product.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'List of products'
        context['name'] = 'products'
        context['create_url'] = reverse_lazy('nynet:create_product')
        return context


class ProductDatatableView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'product/datatable-product.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = [i.toJSON() for i in Product.objects.all()]
            else:
                data['error'] = 'No action sent'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Datatable of products'
        context['name'] = 'products'
        context['action'] = 'searchdata'
        context['create_url'] = reverse_lazy('nynet:create_product')
        context['update_url'] = reverse_lazy('nynet:update_product')
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/create-product.html'
    success_url = reverse_lazy('nynet:product_list')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = dict()
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No action sent'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create products'
        context['action'] = 'add'
        context['list_url'] = reverse_lazy('nynet:product_list')
        return context


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/create-product.html'
    success_url = reverse_lazy('nynet:product_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No action sent'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update product'
        context['list_url'] = reverse_lazy('nynet:product_list')
        context['action'] = 'edit'
        return context


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'delete-ajax.html'
    success_url = reverse_lazy('nynet:product_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete product'
        context['name'] = 'product'
        context['list_url'] = reverse_lazy('nynet:product_list')
        return context


# Invoice
class InvoiceDatatableView(LoginRequiredMixin, ListView):
    model = Invoice
    template_name = 'invoice/datatable-invoice.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Invoice.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'No action sent'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Datatable of invoices'
        context['name'] = 'invoices'
        context['create_url'] = reverse_lazy('nynet:create_invoice')
        context['action'] = 'searchdata'
        context['update_url'] = 'nynet:update_invoice'
        return context


class InvoiceCreateView(LoginRequiredMixin, CreateView):
    model = Invoice
    form_class = InvoiceForm
    template_name = 'invoice/create-invoice.html'
    success_url = reverse_lazy('nynet:datable_invoice')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'search_products':
                data = []
                prods = Product.objects.filter(name__icontains=request.POST['term'])[0:10]
                for i in prods:
                    item = i.toJSON()
                    item['value'] = i.name
                    data.append(item)
            elif action == 'add':
                vents = json.loads(request.POST['vents'])
                print(vents)
                invoice = Invoice()
                invoice.date_joined = vents['date_joined']
                invoice.customer_id = vents['customer']
                invoice.employee_id = vents['employee']
                invoice.subtotal = float(vents['subtotal'])
                invoice.iva = float(vents['iva'])
                invoice.total = float(vents['total'])

                for i in vents['products']:
                    invoice.list_of_products_id = i['id']

                invoice.save()
            else:
                data['error'] = 'No action sent'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create invoice'
        context['action'] = 'add'
        context['list_url'] = reverse_lazy('nynet:datable_invoice')
        return context


class InvoiceUpdateView(LoginRequiredMixin, UpdateView):
    model = Invoice
    form_class = InvoiceForm
    template_name = 'invoice/create-invoice.html'
    success_url = reverse_lazy('nynet:datable_invoice')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No action sent'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update invoice'
        context['list_url'] = reverse_lazy('nynet:datable_invoice')
        context['action'] = 'edit'
        return context


class InvoiceDeleteView(LoginRequiredMixin, DeleteView):
    model = Invoice
    template_name = 'delete-ajax.html'
    success_url = reverse_lazy('nynet:datable_invoice')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete invoice'
        context['name'] = 'invoice'
        context['list_url'] = reverse_lazy('nynet:datable_invoice')
        return context


# Inventory

class InventoryDatatableView(LoginRequiredMixin, ListView):
    model = Inventory
    template_name = 'inventory/datatable-inventory.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:

core/nynet/templates/invoice/create-invoice-org.html
{% extends 'form-ajax.html' %}
{% block form %}
    <div class="field">
        <label class="label is-medium">{{ form.list_of_products.label }}</label>
        <div class="select is-multiple">
            {{ form.list_of_products }}
        </div>
        <a class="button" href="{% url 'nynet:create_inventory' %}">
                <span class="icon is-small">
                    <i class="fa-solid fa-plus"></i>
                </span>
        </a>
    </div>
    <div class="field">
        <label class="label is-medium">{{ form.customer.label }}</label>
        <div class="select">
            {{ form.customer }}

        </div>
        <a class="button" href="{% url 'nynet:create_customer' %}">
                <span class="icon is-small">
                    <i class="fa-solid fa-plus"></i>
                </span>
        </a>
    </div>
    <div class="field">
        <label class="label is-medium">{{ form.employee.label }}</label>
        <div class="select">
            {{ form.employee }}

        </div>
    </div>
    <div class="field">
        <label class="label is-medium">{{ form.iva.label }}</label>
        <div class="control has-icons-left">
            {{ form.iva }}
            <span class="icon is-small is-left">
                    <i class="fa-solid fa-dollar-sign"></i>
                </span>
        </div>
    </div>
    <div class="field">
        <label class="label is-medium">{{ form.subtotal.label }}</label>
        <div class="control has-icons-left">
            {{ form.subtotal }}
            <span class="icon is-small is-left">
                    <i class="fa-solid fa-dollar-sign"></i>
                </span>
        </div>
    </div>
    <div class="field">
        <label class="label is-medium">{{ form.total.label }}</label>
        <div class="control has-icons-left">
            {{ form.total }}
            <span class="icon is-small is-left">
                    <i class="fa-solid fa-dollar-sign"></i>
                </span>
        </div>
    </div>
{% endblock %}

core/nynet/templates/invoice/create-invoice.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/jquery.dataTables.min.css"
          integrity="sha512-1k7mWiTNoyx2XtmI96o+hdjP8nn0f3Z2N4oF/9ZZRgijyV4omsKOXEnqL1gKQNPy2MTSP9rIEWGcH/CInulptA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"
            integrity="sha512-BkpSL20WETFylMrcirBahHfSnY++H2O1W+UnEEO4yNIl+jI2+zowyoGJpbtk6bx97fBXf++WJHSSK2MV4ghPcg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/dataTables.dataTables.min.js"
            integrity="sha512-fQmyZE5e3plaa6ADOXBM17WshoZzDIvo7sR4GC1VsmSKqm13Ed8cO2kPwFPAOoeF0RcdhuQQlPq46X/HnPmllg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.6.0/dt-1.12.1/r-2.3.0/datatables.min.css"/>


    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"
            integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"
          integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>




    <script src="{% static 'js/datatable.js' %}"></script>
    <script src="{% static 'invoice/js/humanize.min.js' %}"></script>
    <script src="{% static 'invoice/js/form.js' %}"></script>

{% endblock %}

{% block content %}
    <form method="post" action="." enctype="multipart/form-data">


        {{ crsf_token }}

        <input type="hidden" name="action" value="{{ action }}">

        {% if form.errors %}
            <div class="notification is-danger is-light">
                <p class="is-size-4"><i class="fa-solid fa-triangle-exclamation"></i> Error</p>
                <button class="delete"></button>
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}

                    {% endfor %}

                </ul>
            </div>
        {% endif %}
        <hr>
        <div class="columns">
            <div class="column is-three-quarters">
                <div class="card ">
                    <div class="card-header has-background-black-ter">
                        <div class="card-header-title">
                            <p class="title is-4 has-text-white">Details of product</p>
                        </div>
                        <div class="card-header-icon">
                            <i class="fa-solid fa-boxes-stacked"></i>
                        </div>
                    </div>
                    <div class="card-content has-background-grey-darker">
                        <div class="field">
                            <label class="label is-medium">Search Product</label>
                            <div class="field has-addons">
                                <div class="control">
                                    <input class="input" type="text" placeholder="Enter a product description"
                                           name="search" autocomplete="false">
                                </div>
                                <div class="control">
                                    <a class="button is-danger btnCleanSearch">
                                        <i class="fa-solid fa-xmark"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <button type="button" class="button is-danger btnRemoveAll">Delete all items <i
                                class="fa-solid fa-trash"></i></button>
                        <hr>
                        <div class="has-text-white">
                            <table id="table" class="table is-striped is-fullwidth has-text-white has-background-dark">
                                <thead>
                                <tr>
                                    <th class="has-text-white"><abbr title="Delete">Del</abbr></th>
                                    <th class="has-text-white"><abbr title="Product">Pro</abbr></th>
                                    <th class="has-text-white"><abbr title="Sales price">SP</abbr></th>
                                    <th class="has-text-white"><abbr title="Amount">Amo</abbr></th>
                                    <th class="has-text-white"><abbr title="Subtotal">Sub</abbr></th>
                                </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card ">
                    <div class="card-header has-background-black-ter">
                        <div class="card-header-title">
                            <p class="title is-4 has-text-white">Details of Sale</p>
                        </div>
                        <div class="card-header-icon">
                            <i class="fa-solid fa-cart-shopping"></i>
                        </div>
                    </div>
                    <div class="card-content has-background-grey-darker">
                        <div class="field">
                            <label class="label">{{ form.date_joined.label }}</label>
                            <div class="control">
                                {{ form.date_joined }}
                            </div>
                            <div class="field">
                                <label class="label is-medium">{{ form.customer.label }}</label>
                                <div class="select">
                                    {{ form.customer | attr:'name:customer' }}

                                </div>
                                <a class="button" href="{% url 'nynet:create_customer' %}">
                                <span class="icon is-small">
                                    <i class="fa-solid fa-plus"></i>
                                </span>
                                </a>
                            </div>
                            <div class="field">
                                <label class="label is-medium">{{ form.employee.label }}</label>
                                <div class="select">
                                    {{ form.employee | attr:'name:employee' }}
                                </div>
                            </div>
                            <div class="field">
                                <label class="label is-medium">{{ form.subtotal.label }}</label>
                                <div class="control has-icons-left">
                                    {{ form.subtotal }}
                                    <span class="icon is-small is-left">
                                    <i class="fa-solid fa-dollar-sign"></i>
                                </span>
                                </div>
                            </div>
                            <div class="field">
                                <label class="label is-medium">{{ form.iva.label }}</label>
                                <div class="control has-icons-left">
                                    {{ form.iva }}
                                    <span class="icon is-small is-left">
                                        <i class="fa-solid fa-percent"></i>
                                    </span>
                                </div>
                            </div>
                            <div class="field">
                                <label class="label is-medium">Calculate IVA</label>
                                <div class="control has-icons-left">
                                    <input type="number" readonly class="input" name="ivacalc" value=0.00>
                                    <span class="icon is-small is-left">
                                        <i class="fa-solid fa-percent"></i>
                                    </span>
                                </div>
                            </div>
                            <div class="field">
                                <label class="label is-medium">{{ form.total.label }}</label>
                                <div class="control has-icons-left">
                                    {{ form.total }}
                                    <span class="icon is-small is-left">
                                    <i class="fa-solid fa-dollar-sign"></i>
                                </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="control">
            <button type="submit" class="button is-primary" id="btnSubmit">Send</button>

            <a class="button is-info" href="{{ list_url }}">Cancel</a>
        </div>
    </form>


{% endblock %}

core/nynet/templates/invoice/datatable-invoice-org.html
{% extends 'datatable-ajax.html' %}
{% load static %}
{% block head_list %}
    <script src="{% static 'invoice/js/list.js' %}"></script>
{% endblock %}

{% block thead %}
    <th class="has-text-white">Id</th>
    <th class="has-text-white"><abbr title="List of Products">LOP</abbr></th>
    <th class="has-text-white"><abbr title="Employee">Emp</abbr></th>
    <th class="has-text-white"><abbr title="Customer">Cus</abbr></th>

{% endblock %}

{% block tbody %}


{% endblock %}

core/nynet/templates/invoice/datatable-invoice.html
{% extends 'datatable-ajax.html' %}
{% load static %}
{% block head_list %}
    <script src="{% static 'invoice/js/list.js' %}"></script>
{% endblock %}

{% block thead %}
    <th class="has-text-white">Id</th>
    <th class="has-text-white"><abbr title="List of Products">LOP</abbr></th>
    <th class="has-text-white"><abbr title="Employee">Emp</abbr></th>
    <th class="has-text-white"><abbr title="Customer">Cus</abbr></th>

{% endblock %}

{% block tbody %}


{% endblock %}