config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.nynet.views import home_view
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nynet/', include('core.nynet.urls')),
    path('', home_view, name='home'),
    path('login/', include('core.login.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/nynet/urls.py
from django.urls import path

from core.nynet.views import ProductListView, ProductDatatableView, ProductCreateView, InvoiceDatatableView, \
    InvoiceCreateView, InventoryDatatableView, InventoryCreateView, ProductUpdateView, InvoiceUpdateView, \
    ProductDeleteView, InvoiceDeleteView, CustomerDeleteView, CustomerCreateView, CustomerUpdateView, \
    InventoryUpdateView, CustomerDatatableView, InventoryDeleteView

app_name = 'nynet'

urlpatterns = [
    # Product
    path('products/list/', ProductListView.as_view(), name='product_list'),
    path('products/datatable/', ProductDatatableView.as_view(), name='datable_product'),
    path('products/add/', ProductCreateView.as_view(), name='create_product'),
    path('products/edit/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),

    # Invoice
    path('invoices/datatable/', InvoiceDatatableView.as_view(), name='datable_invoice'),
    path('invoices/add/', InvoiceCreateView.as_view(), name='create_invoice'),
    path('invoices/edit/<int:pk>/', InvoiceUpdateView.as_view(), name='update_invoice'),
    path('invoices/delete/<int:pk>/', InvoiceDeleteView.as_view(), name='delete_invoice'),

    # Inventory
    path('inventories/datatable/', InventoryDatatableView.as_view(), name='datable_inventory'),
    path('inventories/add/', InventoryCreateView.as_view(), name='create_inventory'),
    path('inventories/edit/<int:pk>/', InventoryUpdateView.as_view(), name='update_inventory'),
    path('inventories/delete/<int:pk>/', InventoryDeleteView.as_view(), name='delete_inventory'),

    # Customer
    path('customers/datatable/', CustomerDatatableView.as_view(), name='datable_customer'),
    path('customers/add/', CustomerCreateView.as_view(), name='create_customer'),
    path('customers/edit/<int:pk>/', CustomerUpdateView.as_view(), name='update_customer'),
    path('customers/delete/<int:pk>/', CustomerDeleteView.as_view(), name='delete_customer'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/3dc2b2376d.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"
            integrity="sha512-zP5W8791v1A6FToy+viyoyUUyjCzx+4K8XZCKzW28AnCoepPNIXecxh9mvGuy3Rt78OzEsU+VCvcObwAMvBAww=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.css"
          integrity="sha512-0V10q+b1Iumz67sVDL8LPFZEEavo6H/nBSyghr7mm9JEQkOAm91HNoZQRvQdjennBb/oEuW+8oZHVpIKq+d25g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <script src="{% static 'js/functions.js' %}"></script>
    <script src="{% static 'js/burger.js' %}"></script>


    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">

    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}{% endblock %}
{% block footer %}
    {% include 'components/footer.html' %}
{% endblock %}
{% block javascript %}

{% endblock %}
</body>
</html>

templates/datatable-ajax.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/jquery.dataTables.min.css"
          integrity="sha512-1k7mWiTNoyx2XtmI96o+hdjP8nn0f3Z2N4oF/9ZZRgijyV4omsKOXEnqL1gKQNPy2MTSP9rIEWGcH/CInulptA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"
            integrity="sha512-BkpSL20WETFylMrcirBahHfSnY++H2O1W+UnEEO4yNIl+jI2+zowyoGJpbtk6bx97fBXf++WJHSSK2MV4ghPcg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/dataTables.dataTables.min.js"
            integrity="sha512-fQmyZE5e3plaa6ADOXBM17WshoZzDIvo7sR4GC1VsmSKqm13Ed8cO2kPwFPAOoeF0RcdhuQQlPq46X/HnPmllg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.6.0/dt-1.12.1/r-2.3.0/datatables.min.css"/>


    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"
            integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"
          integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>


    <script src="{% static 'js/datatable.js' %}"></script>
    {% block head_list %}{% endblock %}
{% endblock %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="hero-body">
        <div class="container has-text-centered">
            <p class="title has-text-white">{{ title }}</p>
            <p class="subtitle has-text-white">If you want to add more {{ name }} <a href="{{ create_url }}">Click
                Here</a></p>
        </div>
    </div>
    <div class="container has-text-white">
        <table id="table" class="table is-striped is-fullwidth has-text-white has-background-dark">
            <thead>
            <tr>
                {% block thead %}

                {% endblock %}
                <th class="has-text-white">Options</th>
            </tr>
            </thead>
            <tbody>
            {% block tbody %}

            {% endblock %}
            </tbody>
        </table>
    </div>


{% endblock %}

templates/datatable.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/bm/jq-3.6.0/dt-1.12.1/r-2.3.0/datatables.min.css"/>

    <script type="text/javascript"
            src="https://cdn.datatables.net/v/bm/jq-3.6.0/dt-1.12.1/r-2.3.0/datatables.min.js"></script>
{% endblock %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="hero-body">
        <div class="container has-text-centered">
            <p class="title has-text-white">{{ title }}</p>
            <p class="subtitle has-text-white">If you want to add more {{ name }} <a href="{{ create_url }}">Click
                Here</a></p>
        </div>
    </div>
    <div class="container has-text-white">
        <table id="table" class="table is-striped is-fullwidth has-text-white has-background-dark">
            <thead>
            <tr>
                {% block thead %}

                {% endblock %}
                <th class="has-text-white">Options</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>

                {% block tbody %}

                {% endblock %}

                <td>
                    <a href=" {% url 'nynet:update_product' object.id %} " class="has-text-success"><i class="fa-solid fa-pen-to-square"></i>Edit</a>
                    <a href="{% url 'nynet:delete_product' object.id %}" class="has-text-danger"><i class="fa-solid fa-trash"></i>Delete</a>
                </td>


            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block javascript %}
    <script type="application/javascript" src="{% static 'js/datatable.js' %}"></script>
{% endblock %}

templates/delete-ajax.html
{% extends 'base.html' %}
{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <form method="post" action="." enctype="multipart/form-data">

        {{ crsf_token }}
        <article class="message is-danger">
            <div class="message-header">
                <p>Are you sure you want to delete this {{ name }} {{ object.name }}?</p>
            </div>
            <div class="message-body">
                If you delete this {{ name }} you will not be able to recover, this action has no correction, take the
                necessary measures before deleting this.
            </div>
        </article>

        <div class="control">
            <button type="submit" class="button is-danger">Delete</button>

            <a class="button is-info" href="{{ list_url }}">Cancel</a>
        </div>

    </form>

    <script>

            $('form').on('submit', function (e) {
                e.preventDefault();
                {#var parameters = $(this).serializeArray();#}
                var parameters = new FormData(this);

                ajax_with_confirm(window.location.pathname,'Delete','Are you sure of delete this?',parameters,function (){
                location.href = '{{ list_url }}';
            })

            });
        </script>

{% endblock %}

templates/delete.html
{% extends 'base.html' %}
{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <form method="post" action="." enctype="multipart/form-data">

        {{ crsf_token }}
        <article class="message is-danger">
            <div class="message-header">
                <p>Are you sure you want to delete this {{ name }} {{ object.name }}?</p>
            </div>
            <div class="message-body">
               If you delete this {{ name }} you will not be able to recover, this action has no correction, take the necessary measures before deleting this.
            </div>
        </article>

        <div class="control">
            <button type="submit" class="button is-danger">Delete</button>

            <a class="button is-info" href="{{ list_url }}">Cancel</a>
        </div>

    </form>


{% endblock %}

templates/form-ajax.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <script type="application/javascript" src="{% static 'js/modal.js' %}"></script>
{% endblock %}
{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <form method="post" action="." enctype="multipart/form-data">


        {{ crsf_token }}

        <input type="hidden" name="action" value="{{ action }}">

        {% if form.errors %}
            <div class="notification is-danger is-light">
                <p class="is-size-4"><i class="fa-solid fa-triangle-exclamation"></i> Error</p>
                <button class="delete"></button>
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}

                    {% endfor %}

                </ul>
            </div>
        {% endif %}
        {% block form %}

        {% endblock %}


        <div class="control">
            <button type="submit" class="button is-primary" id="btnSubmit">Send</button>

            <a class="button is-info" href="{{ list_url }}">Cancel</a>
        </div>
    </form>


    <script>

        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);

            ajax_with_confirm(window.location.pathname, 'Create', 'Are you sure of create this?', parameters, function () {
                location.href = '{{ list_url }}';
            })

        });
    </script>

{% endblock %}

{% block javascript %}
    <script type="application/javascript" src="{% static 'js/close_notification.js' %}"></script>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <form method="post" action="." enctype="multipart/form-data" id="ajax">

        {{ crsf_token }}
        <input type="hidden" name="action" value="{{ action }}">
        {% if form.errors %}
            <div class="notification is-danger is-light">
                <p class="is-size-4"><i class="fa-solid fa-triangle-exclamation"></i> Error</p>
                <button class="delete"></button>
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}

                    {% endfor %}

                </ul>
            </div>
        {% endif %}
        {% block form %}

        {% endblock %}
        <div class="control">
            <button type="submit" class="button is-primary" id="btnSubmit">Send</button>
        </div>
        <div class="control">
            <a class="button is-info" href="{{ list_url }}">Cancel</a>
        </div>
    </form>


{% endblock %}

{% block javascript %}
    <script type="application/javascript" src="{% static 'js/close_notification.js' %}"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/hello-parallax.css' %}">
{% endblock %}
{% block title %}
    Index
{% endblock %}

{% block content %}
    <section class="hero is-medium">
        <div class="hero-body">
            <div class="container">
                <h1 class="title is-1 ">Welcome to NyNet</h1>
                <h2 class="subtitle">
                    This project is developed independently.
                    <br>
                    It consists of an electronic invoicing system focused on the sales made by a company, where
                    a model of random promotions is implemented for customers.
                </h2>
                <a href="#" class="button is-white is-medium is-inverted">Learn More&ensp;<i
                        class="fa-solid fa-chevron-right"></i></a>
            </div>
        </div>
    </section>
    <section id="parallax-1" class="hero is-large ">
        <div class="hero-body">
            <div class="container">
                <div class="columns">
                    <div class="column is-6 is-offset-6">
                        <h1 class="title is-1 ">To login or create a new user</h1>
                        <hr class="content-divider">
                        <h2 class="subtitle">
                            To access the system as a company employee, please <a href="#">Log in</a> or <a href="#">create</a>
                            a new user. If you need an account as a supervisor or administrator, please contact your
                            company to securely register.
                        </h2>
                        <a href="#" class="button is-white is-inverted">Next&ensp;<i
                                class="fa-solid fa-chevron-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="parallax-2" class="hero is-large ">
        <div class="hero-body">
            <div class="container">
                <div class="columns">
                    <div class="column is-6">
                        <h1 class="title is-1 ">About us</h1>
                        <hr class="content-divider">
                        <h2 class="subtitle">
                            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque
                            veritatis sequi natus minima distinctio ullam deleniti quasi quisquam autem deserunt.
                        </h2>
                        <a href="#" class="button is-white is-inverted">Next&ensp;<i
                                class="fa-solid fa-chevron-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="cta va">
        <div class="container">
            <div class="columns">
                <div class="column is-6">
                    <h1 class="title is-1 ">Contact us</h1>
                    <hr class="content-divider">
                    <h2 class="subtitle">
                        For technical support, please contact us by any of the following means
                        <br>
                        <a>bscortes94@ucatolica.edu.co</a>
                        <br>
                        <a>jlperez68@ucatolica.edu.co</a>
                        <br>
                        <a>jsramirez444@ucatolica.edu.co</a>
                    </h2>
                </div>
                <div class="column is-6">
                    <div class="field">
                        <label class="label">Name</label>
                        <div class="control">
                            <input class="input is-medium" type="text" placeholder="Jon Snow">
                        </div>
                    </div>
                    <br>
                    <div class="field">
                        <label class="label">Email</label>
                        <div class="control">
                            <input class="input is-medium" type="email" placeholder="jon@winterfell.com">
                        </div>
                    </div>
                    <br>
                    <div class="field is-grouped">
                        <div class="control">
                            <button class="button is-white is-rounded is-outlined">Submit</button>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </section>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}
{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="hero-body">
        <div class="container has-text-centered">
            <p class="title has-text-white">{{ title }}</p>

            <p class="subtitle has-text-white">If you want to add more {{ name }} <a href="{{ create_url }}">Click
                Here</a></p>
        </div>
    </div>
    <div class="listContainer">
        <section class="list-view">
            {% for object in object_list %}

                <div class="card">
                    <div class="card-image">
                        <figure class="image is-4by3">
                            {% block card-image %}

                            {% endblock %}
                        </figure>
                    </div>
                    <div class="card-content">
                        <div class="content">
                            {% block card-content %}

                            {% endblock %}
                            <div class="edit-content">
                                <a href="{% url 'nynet:update_product' object.id %}" class="has-text-success"><i class="fa-solid fa-pen-to-square"></i>Edit</a>
                                <a href="{% url 'nynet:delete_product' object.id %}" class="has-text-danger is-pulled-right"><i class="fa-solid fa-trash"></i>Delete</a>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </section>
    </div>
{% endblock %}