config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.nynet.views import home_view
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nynet/', include('core.nynet.urls')),
    path('', home_view, name='home'),
    path('login/', include('core.login.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/nynet/urls.py
from django.urls import path

from core.nynet.views import ProductListView, ProductDatatableView, ProductCreateView, InvoiceDatatableView, \
    InvoiceCreateView, InventoryDatatableView, InventoryCreateView, ProductUpdateView, InvoiceUpdateView, \
    ProductDeleteView, InvoiceDeleteView, CustomerDeleteView, CustomerCreateView, CustomerUpdateView, \
    InventoryUpdateView, CustomerDatatableView, InventoryDeleteView

app_name = 'nynet'

urlpatterns = [
    # Product
    path('products/list/', ProductListView.as_view(), name='product_list'),
    path('products/datatable/', ProductDatatableView.as_view(), name='datable_product'),
    path('products/add/', ProductCreateView.as_view(), name='create_product'),
    path('products/edit/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),

    # Invoice
    path('invoices/datatable/', InvoiceDatatableView.as_view(), name='datable_invoice'),
    path('invoices/add/', InvoiceCreateView.as_view(), name='create_invoice'),
    path('invoices/edit/<int:pk>/', InvoiceUpdateView.as_view(), name='update_invoice'),
    path('invoices/delete/<int:pk>/', InvoiceDeleteView.as_view(), name='delete_invoice'),

    # Inventory
    path('inventories/datatable/', InventoryDatatableView.as_view(), name='datable_inventory'),
    path('inventories/add/', InventoryCreateView.as_view(), name='create_inventory'),
    path('inventories/edit/<int:pk>/', InventoryUpdateView.as_view(), name='update_inventory'),
    path('inventories/delete/<int:pk>/', InventoryDeleteView.as_view(), name='delete_inventory'),

    # Customer
    path('customers/datatable/', CustomerDatatableView.as_view(), name='datable_customer'),
    path('customers/add/', CustomerCreateView.as_view(), name='create_customer'),
    path('customers/edit/<int:pk>/', CustomerUpdateView.as_view(), name='update_customer'),
    path('customers/delete/<int:pk>/', CustomerDeleteView.as_view(), name='delete_customer'),

]

templates/components/footer.html
<footer class="footer">
    <div class="content has-text-centered">
        <p>
            <strong>NyNet</strong> by <a href="https://c.tenor.com/29Ok5pc0ivAAAAAM/gatinho-gato.gif">Chayanne Ozuna</a>. The source code is licensed by
            <a href="https://thumbs.gfycat.com/SnarlingSadHorseshoebat-size_restricted.gif">Three Friends</a>. The website content
            is licensed by <a href="https://c.tenor.com/_5Jd5J9n5-QAAAAC/baile-del-trolleo.gif">Me</a>.
        </p>
    </div>
</footer>

templates/components/modal.html
<div id="modal-js-example" class="modal">
    <form method="post" action="." enctype="multipart/form-data">
        <div class="modal-background"></div>
        <div class="modal-card">
            <header class="modal-card-head">
                <p class="modal-card-title">Modal title</p>
                <button class="delete" aria-label="close"></button>
            </header>

            <section class="modal-card-body">
                {{ form.as_p }}
            </section>
            <footer class="modal-card-foot">
                <button class="button is-success">Save changes</button>
                <button class="button">Cancel</button>
            </footer>
        </div>
    </form>
</div>

templates/components/navbar.html
{% load static %}

<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="https://c.tenor.com/QNrjCFYpJIwAAAAM/pigeon-fly.gif">

            <figure class="image">
                <i><img src="{% static 'img/NYnet-Logo.svg' %}" alt="Nynet"></i>
            </figure>
        </a>

        <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="{% url 'home' %}"> Home </a>
            {% if user.is_authenticated %}
                <a class="navbar-item" href="{% url 'nynet:product_list' %}"> My products </a>
                {% if user.is_staff %}
                    <a class="navbar-item" href="{% url 'nynet:create_invoice' %}"> Sell </a>
                    <a class="navbar-item" href="{% url 'nynet:create_product' %}"> Create </a>
                {% elif user.role == 2 %}
                    <a class="navbar-item" href="{% url 'nynet:create_invoice' %}"> Sell </a>
                {% endif %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link"> Datatables </a>

                    <div class="navbar-dropdown">
                        <a href="{% url 'nynet:datable_product' %}" class="navbar-item"> Product </a>
                        <a href="{% url 'nynet:datable_invoice' %}" class="navbar-item"> Invoice </a>
                        <a href="{% url 'nynet:datable_inventory' %}" class="navbar-item"> Inventory </a>
                        <a href="{% url 'nynet:datable_customer' %}" class="navbar-item"> Customer </a>
                    </div>
                </div>
            {% endif %}
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link"> More </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item"> About </a>
                    <a class="navbar-item"> Jobs </a>
                    <a class="navbar-item"> Contact </a>
                    <hr class="navbar-divider"/>
                    <a class="navbar-item"> Report an issue </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                {% if user.is_authenticated %}

                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link is-arrowless">
                            <figure class="image is-32x32">
                                <img
                                        class="is-rounded"
                                        src="{{ user.get_image }}" alt="{{ user.username }}"/>
                            </figure>

                        </a>

                        <div class="navbar-dropdown is-right">
                            <a class="navbar-item"> Account </a>
                            <a class="navbar-item"> Settings </a>
                            <a class="navbar-item"> Support </a>
                            <hr class="navbar-divider"/>
                            <a class="navbar-item" href="{% url 'logout' %}">
                                Sing out
                            </a>
                        </div>
                    </div>
                {% else %}
                    <div class="buttons">
                        <a class="button is-primary" href="">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button is-light" href="{% url 'login' %}">
                            Log in
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>